### ISSUE TITLE
[BUG] entry.profile.name must not be null

### ISSUE THREAD

**Issue by Chanakan55991** [Wolfsurge/Paragon#14]
**Describe the bug**
when you tried to join a server from time to time, this exception will be shown on the screen and would not let you connect to a server.

**To Reproduce**
The exception happened randomly when you tried to join/leave a server.

**Expected behavior**
no exception should be thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/80865605/179505117-2a50143c-a8ad-4e81-85ac-99a184686777.png)

name from the game profile could be null from time to time, I do not know the exact reason why it would be null and so I did not make a pull request.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by noatmc** [comment]
woah! another thailand block game utility mod maker!

**Comment by Wolfsurge** [comment]
make a pr and null check it

**Comment by Wolfsurge** [comment]
EventFactory
