### ISSUE TITLE
[BUG] Client Crashed

### ISSUE THREAD

**Issue by TikyMan** [Wolfsurge/Paragon#34]
Client Crashed Im Use TL Legacy ForgeOptifine 1.12.2

**Comment by Wolfsurge** [comment]
can you provide a crash log?

**Comment by therealbush** [comment]
lawl

**Comment by Wolfsurge** [comment]
are you using the Github Workflows build?

It doesn't work. You will have to build from source TWICE, and then the build will work. probably. Or just download the pre compiled jar from the releases tab.

**Comment by GentlemanMC** [comment]
user issue

**Comment by GentlemanMC** [comment]
stop playing cracked

**Comment by GentlemanMC** [comment]
and get funds

**Comment by KassuK1** [comment]
Stop playing cracked and buy the game boom fixed

**Comment by Wolfsurge** [comment]
This is todo with MixinGradle. Download latest build from workflows, and it should work.
