### ISSUE TITLE
[BUG] Crystal Aura Crash after turn on

### ISSUE THREAD

**Issue by KaliCyanide** [Wolfsurge/Paragon#35]
The crystal aura crash

**Comment by KaliCyanide** [comment]
[latest.log](https://github.com/Wolfsurge/Paragon/files/9592903/latest.log)

**Comment by Wolfsurge** [comment]
Can you see if this issue is reproduceable with the latest build? You can get it [here](https://github.com/Wolfsurge/Paragon/actions/runs/3073891306)

**Comment by KaliCyanide** [comment]
it work very based
