### ISSUE TITLE
[BUG]Paragon gui

### ISSUE THREAD

**Issue by ImKindaSus** [Wolfsurge/Paragon#36]
**Describe the bug**
Small but very anoying mis cut(i guess)

**To Reproduce**
Turn on paragon menu in main menu

**Expected behavior**
it suppouse to be to the end

**Screenshots**
(https://youtu.be/nAsTDyLrD60)

**Desktop (please complete the following information):**

- OS: win10

**Comment by Wolfsurge** [comment]
no :troll:

**Comment by Wolfsurge** [comment]
jk I'll fix when I get home
