### ISSUE TITLE
[BUG] NameTags On Crash MineCraft

### ISSUE THREAD

**Issue by NCPUser** [Wolfsurge/Paragon#42]

**Comment by Wolfsurge** [comment]
Can you provide a crash log? Any additional context?

**Comment by NCPUser** [comment]
[2022-11-27-7.log.gz](https://github.com/Wolfsurge/Paragon/files/10098910/2022-11-27-7.log.gz)
ok

**Comment by Wolfsurge** [comment]
Fairly certain this isn't to do with Nametags - there isn't actually an error in the crash log given.

**Comment by NCPUser** [comment]
Okey im new crash log wait

**Comment by NCPUser** [comment]
[latest.log](https://github.com/Wolfsurge/Paragon/files/10149510/latest.log)
