### ISSUE TITLE
[IMPROVEMENT] mc null checks

### ISSUE THREAD

**Issue by cart69420** [Wolfsurge/Paragon#45]
cut off those "minecraft.anyNull" checks cause too excessive
do with reflections(?) instead

**Comment by Wolfsurge** [comment]
Basically every client uses a null check, because some modules might not need to use `minecraft.world` or `minecraft.player`.  

All `minecraft.anyNull` does is check if `mineccraft.player` or `minecraft.world` is null.

**Comment by SooStrator1136** [comment]
+ its inlined so it _literally_ is the same as manually nullchecking mc.player and mc.world
