### ISSUE TITLE
[BUG]Issues with some of the things that I've found

### ISSUE THREAD

**Issue by ImKindaSus** [Wolfsurge/Paragon#49]
1)You can't move hub window, when it clearly should
2)Hub is overlapping 'Tab to open search' thing'
3)Change log thing is fucked(as can be seen here https://imgur.com/a/MHDkIvU)
4)Purple line is off on ShulkerViewer module(as can be seen here)
![image](https://user-images.githubusercontent.com/72939961/206702496-3e44966d-5140-4acd-952a-73a8fb3dceab.png)

OS:win 10

**Comment by Wolfsurge** [comment]
Hub window is locked in place. I'll fix the rest when I get home.

**Comment by ImKindaSus** [comment]
Thank you
