### ISSUE TITLE
[FEATURE] Games

### ISSUE THREAD

**Issue by ImKindaSus** [Wolfsurge/Paragon#54]
I would like to have simple classic games like snake or Tetris, or idk chess bot(last one is a joke) inside the client to play them while I'm waiting for something

**Comment by Wolfsurge** [comment]
yea sure ill do that at some point

**Comment by ImKindaSus** [comment]
And you've promised them)

**Comment by GentlemanMC** [comment]
bloat

**Comment by ImKindaSus** [comment]
> bloat
> 
> 

- [ ] Why you think so? There is already bloat in the client so why not add some actually good bloat
