### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by Zane2b2t** [Wolfsurge/Paragon#6]
Removes me then releases 2 days later lol
I didnt even use the client but ok

**Comment by Wolfsurge** [comment]
> Removes me then releases 2 days later lol
> I didnt even use the client but ok

You got ratioed by sable and void 


please be quiet

**Comment by therealbush** [comment]
> Removes me then releases 2 days later lol I didnt even use the client but ok

cope lol

**Comment by KassuK1** [comment]
L

**Comment by TwoThreeTwo** [comment]
kek

**Comment by SooStrator1136** [comment]
> kek

232

**Comment by TwoThreeTwo** [comment]
SooStrator2236
